language: ruby
rvm:
- 2.0.0
deploy:
  provider: rubygems
  api_key:
    secure: Yh9SvLN3oX7irNROrMWci4sFXhRi6bOte0tyFaSkF1EGjX78Bl3ja/8cVVXIPO6QNTFl8z1nOtw3vCny4sHqwUoGVszGxiHlBHfHSGd5jFBx+9ctT5wZrVEaspzBd+rIUuXOhV1276IoQPcpI4BkYRfAdnOsqvT5bW2N4bvaKEE=
  gem: zaws
  on:
    tags: true
    repo: zynxhealth/zaws
